name: "push-sync-template"
author: "patacoing"
description: "Push updates from a template repository to repositories that have been created from it."
branding:
  icon: "activity"
  color: "white"

inputs:
  organization:
    description: "GitHub organization name."
    required: true
  template_repository_name:
    description: "Template repository name."
    required: true
  commit_message:
    description: "Commit message for the sync operation."
    required: false
  pr_title:
    description: "Pull request title."
    required: false
  pr_body:
    description: "Pull request body."
    required: false
  default_reviewers:
    description: "Default reviewers for the pull request. Specify GitHub usernames separated by commas."
    required: false
  request_review_from_copilot:
    description: "Request review from GitHub Copilot. Set to true to enable Copilot review requests."
    required: false
  github_pat:
    description: "GitHub Personal Access Token (PAT) with: 
                 - `repo` scope for private repositories,
                 - `workflow` scope for workflow dispatch,
                 - `admin:org` scope for organization access."
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Sync repositories
      env:
        GITHUB_PAT: ${{ inputs.github_pat }}
        TEMPLATE_REPOSITORY_NAME: ${{ inputs.template_repository_name }}
        COMMIT_MESSAGE: ${{ inputs.commit_message }}
        PR_TITLE: ${{ inputs.pr_title }}
        PR_BODY: ${{ inputs.pr_body }}
        DEFAULT_REVIEWERS: ${{ inputs.default_reviewers }}
        REQUEST_REVIEW_FROM_COPILOT: ${{ inputs.request_review_from_copilot }}
        ORGANIZATION: ${{ inputs.organization }}
        GITHUB_ACTOR: ${{ github.actor }}
      shell: bash
      id: sync
      run: ${{ github.action_path }}/src/sync_repositories.sh