name: "push-sync-template"
author: "patacoing"
description: "Push updates from a template repository to repositories that have been created from it."
branding:
  icon: "activity"
  color: "white"

inputs:
  organization:
    description: "GitHub organization name."
    required: true
  template_repository_name:
    description: "Template repository name."
    required: true
  commit_message:
    description: "Commit message for the sync operation. If not provided, a default message will be used. You can use the following variables in the message:
                 - `${template_repository_name}`: Name of the template repository
                 - `${branch_name}`: Name of the branch being created
                 - `${latest_template_commit}`: Latest commit hash of the template repository"
    required: false
  branch_name:
    description: "Branch name for the sync operation. If not provided, a default branch name will be generated based on the latest commit of the template repository. You can use the following variables in the branch name:
                 - `${template_repository_name}`: Name of the template repository
                 - `${latest_template_commit}`: Latest commit hash of the template repository"
    required: false
  pr_title:
    description: "Pull request title. If not provided, a default title will be used. You can use the following variables in the title:
                 - `${template_repository_name}`: Name of the template repository
                 - `${branch_name}`: Name of the branch being created"
    required: false
  pr_body:
    description: "Pull request body. If not provided, a default body will be used. You can use the following variables in the body:
                 - `${template_repository_name}`: Name of the template repository
                 - `${branch_name}`: Name of the branch being created
                 - `${latest_template_commit}`: Latest commit hash of the template repository"
    required: false
  default_reviewers:
    description: "Default reviewers for the pull request. Specify GitHub usernames separated by commas."
    required: false
  request_review_from_copilot:
    description: "Request review from GitHub Copilot. Set to true to enable Copilot review requests."
    required: false
  github_pat:
    description: "GitHub Personal Access Token (PAT) with: 
                 - `repo` scope for private repositories,
                 - `workflow` scope for workflow dispatch,
                 - `admin:org` scope for organization access."
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Sync repositories
      env:
        GITHUB_PAT: ${{ inputs.github_pat }}
        TEMPLATE_REPOSITORY_NAME: ${{ inputs.template_repository_name }}
        COMMIT_MESSAGE: ${{ inputs.commit_message }}
        BRANCH_NAME: ${{ inputs.branch_name }}
        PR_TITLE: ${{ inputs.pr_title }}
        PR_BODY: ${{ inputs.pr_body }}
        DEFAULT_REVIEWERS: ${{ inputs.default_reviewers }}
        REQUEST_REVIEW_FROM_COPILOT: ${{ inputs.request_review_from_copilot }}
        ORGANIZATION: ${{ inputs.organization }}
        GITHUB_ACTOR: ${{ github.actor }}
        GH_TOKEN: ${{ inputs.github_pat }}
      shell: bash
      id: sync
      run: ${{ github.action_path }}/src/sync_repositories.sh